upgraded github.com/gophercloud/utils v0.0.0-20210720165645-8a3ad2ad9e70 => v0.0.0-20220209210848-d0ab9f2a8909
The following conflict occurs:
vendor/github.com/terraform-provider-openstack/terraform-provider-openstack/openstack/data_source_openstack_compute_hypervisor_v2.go:65:35: not enough arguments in call to hypervisors.List
        have (*gophercloud.ServiceClient)
        want (*gophercloud.ServiceClient, hypervisors.ListOptsBuilder)
vendor/github.com/terraform-provider-openstack/terraform-provider-openstack/openstack/data_source_openstack_compute_keypair_v2.go:49:25: not enough arguments in call to keypairs.Get
        have (*gophercloud.ServiceClient, string)
        want (*gophercloud.ServiceClient, string, keypairs.GetOptsBuilder)
vendor/github.com/terraform-provider-openstack/terraform-provider-openstack/openstack/resource_openstack_compute_keypair_v2.go:99:25: not enough arguments in call to keypairs.Get
        have (*gophercloud.ServiceClient, string)
        want (*gophercloud.ServiceClient, string, keypairs.GetOptsBuilder)
vendor/github.com/terraform-provider-openstack/terraform-provider-openstack/openstack/resource_openstack_compute_keypair_v2.go:121:23: not enough arguments in call to keypairs.Delete
        have (*gophercloud.ServiceClient, string)
        want (*gophercloud.ServiceClient, string, keypairs.DeleteOptsBuilder)
vendor/github.com/terraform-provider-openstack/terraform-provider-openstack/openstack/resource_openstack_objectstorage_container_v1.go:216:3: cannot use d.Get("container_read").(string) (type string) as type *string in field value
vendor/github.com/terraform-provider-openstack/terraform-provider-openstack/openstack/resource_openstack_objectstorage_container_v1.go:217:3: cannot use d.Get("container_sync_to").(string) (type string) as type *string in field value
vendor/github.com/terraform-provider-openstack/terraform-provider-openstack/openstack/resource_openstack_objectstorage_container_v1.go:218:3: cannot use d.Get("container_sync_key").(string) (type string) as type *string in field value
vendor/github.com/terraform-provider-openstack/terraform-provider-openstack/openstack/resource_openstack_objectstorage_container_v1.go:219:3: cannot use d.Get("container_write").(string) (type string) as type *string in field value
vendor/github.com/terraform-provider-openstack/terraform-provider-openstack/openstack/resource_openstack_objectstorage_container_v1.go:220:3: cannot use d.Get("content_type").(string) (type string) as type *string in field value

Signed-off-by: Hu Shuai <hus.fnst@fujitsu.com>